name: Python Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Run Black (formatting check)
      run: |
        black --check --diff "ECU Connection/"*.py "Protocol Discovery/"*.py "Data Capture/"*.py

    - name: Run Flake8 (linting)
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 "ECU Connection/"*.py "Protocol Discovery/"*.py "Data Capture/"*.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. Line length set to 100
        flake8 "ECU Connection/"*.py "Protocol Discovery/"*.py "Data Capture/"*.py --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics